### ISSUE TITLE
cachyos_repo

### ISSUE THREAD

**Issue by drmarwat** [CachyOS/cachyos_repo#1]
Hi,
I tried adding the repo to my arch linux as 

[cachyos]
Server = https://github.com/CachyOS/cachyos_repo/tree/master/x86_64
but get following error in terminal after sudo pacman -Syu

error: could not open file /var/lib/pacman/sync/cachyos.db: Unrecognized archive format

**Comment by ptr1337** [comment]
Hey, 

im sorry we just changed today our repo for providing x86-64-v3 packages also. 
Kernels, Librewolf, and some other packages will be available there as Genv3 packages. 

The forum is in work and will be up the comming days with more informations. 
# If you got a x86_64_v3 cpu you can add this and profit automaticly from gen3 packages

#Architecture = x86_64 x86_64_v3 


Please add these two:

# if you dont have a x86-64-v3 supported machine comment that
#[cachyos-x86-64-v3]
#Server = https://aur.cachyos.org/cachyos-aur/x86_64_v3

[cachyos]
Server = https://aur.cachyos.org/cachyos-aur/x86_64

**Comment by ptr1337** [comment]
If you got any keyring issues just manually install this package with sudo pacman -U 

https://cloud.cachyos.org/LUto0/quHENeVa46.zst

**Comment by VildaTech** [comment]
After adding repositories run
`sudo pacman -Sy`
After that run
`sudo pacman -Syu`

**Comment by drmarwat** [comment]
Thanks, I will just test and report back.
